DROP TABLE IF EXISTS MESSAGE;
DROP TABLE IF EXISTS QUEUE;
 
CREATE TABLE MESSAGE (
  MESSAGE_ID VARCHAR(250) AUTO_INCREMENT  PRIMARY KEY,
  QUEUE_ID VARCHAR(250) NOT NULL,
  MESSAGE VARCHAR(250) NOT NULL,
  MESSAGE_TIME VARCHAR(250) DEFAULT NULL
);

  
CREATE TABLE QUEUE (
  QUEUE_ID VARCHAR(250) AUTO_INCREMENT  PRIMARY KEY,
  QUEUE_NAME VARCHAR(250) NOT NULL,
  QUEUE_MAX_LIMIT VARCHAR(250) NOT NULL,
  ADDED_TIME VARCHAR(250) DEFAULT NULL
);